spring.application.name=cerbere-devices-mock

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=cerbere_devices_mock

cerbere.devices-mock.mqtt.broker-url=tcp://localhost:1883
cerbere.devices-mock.mqtt.client-id=cerbere-devices-mock
cerbere.devices-mock.mqtt.base-topic=zigbee2mqtt

cerbere.devices-mock.simulation.fixed-delay-ms=15000
cerbere.devices-mock.simulation.trigger-probability=0.3

server.port=8081
