spring.application.name=cerbere-devices-mock

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=cerbere_devices_mock

spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=fr.cerbere.shared.kafka.JacksonEventSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=fr.cerbere.shared.kafka.JacksonEventDeserializer
spring.kafka.consumer.auto-offset-reset=earliest

cerbere.devices-mock.simulation.fixed-delay-ms=15000
cerbere.devices-mock.simulation.trigger-probability=0.3

cerbere.core.base-url=http://localhost:8082

server.port=8081
