spring.application.name=cerbere-devices-bridge

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=cerbere_devices_bridge

spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=fr.cerbere.shared.kafka.JacksonEventSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=fr.cerbere.shared.kafka.JacksonEventDeserializer
spring.kafka.consumer.auto-offset-reset=earliest

cerbere.devices-bridge.mqtt.broker-url=tcp://localhost:1883
cerbere.devices-bridge.mqtt.client-id=cerbere-devices-bridge
cerbere.devices-bridge.mqtt.base-topic=zigbee2mqtt

server.port=8085
