spring.application.name=cerbere-bff

cerbere.core.base-url=http://localhost:8082
cerbere.devices-mock.base-url=http://localhost:8081
cerbere.history.base-url=http://localhost:8084

cerbere.bff.test-mode.enabled=true

server.port=8083

server.error.include-message=always
server.error.include-binding-errors=never
